# This file lists the dependencies needed to build and test all of pyarbxx.
# # Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: pyarbxx-build
channels:
  - conda-forge
  - defaults
dependencies:
  - automake
  - boost-cpp==1.74.0
  - coreutils
  - cppyy>=2.1.0,<3
  - cppyythonizations>=1.1.3,<2
  - ipywidgets
  - libtool
  - make
  - pytest
  - setuptools
  # valgrind is only needed for make check-valgrind
  # - valgrind
