channel_targets:
  - flatsurf main
channel_sources:
  - flatsurf,conda-forge,defaults
build_flavour:
  - release
  - release
  - style
  - test
  - coverage
  - benchmark
target:
  - libexactreal
  - pyexactreal
  - exactreal
  - exactreal
  - exactreal
  - exactreal
zip_keys:
  - build_flavour
  - target
