channel_targets:
  - flatsurf main
channel_sources:
  - flatsurf,conda-forge,defaults
target:
  - release
  - release
  - style
  - test
  - coverage
  - benchmark
name:
  - libexactreal
  - pyexactreal
  - exact-real
  - exact-real
  - exact-real
  - exact-real
zip_keys:
  - target
  - name
