# conda-smithy assumes that the build number is >= 1000 when building with the new anaconda compilers,
# this probably is not important but make_build_number otherwise complains during the build
# See https://github.com/conda/conda-build/issues/2666 for the missing tag
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = (environ.get('GIT_DESCRIBE_NUMBER')|int + 1000)|string %}
{% set build_string = "master_" + build_number %}
{% set flavour = environ.get('FLAVOUR', 'build')|string %}

package:
  name: libexactreal
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: {{ build_string }}
  # e-antic is not available for Windows & macOS
  skip: True  # [win]
  skip: True  # [osx]
  script:
    - source ./recipe/cflags.sh
    # /tmp/secrets contains some CI-injected credentials to services such as
    # coveralls or ASV.
    - source /tmp/secrets
    - ./recipe/build-{{ flavour }}.sh
    # conda-build can currently not copy build-artifacts over to the testing
    # stage, so we can only run make check if we rebuild everything. Therefore,
    # we run make check as part of the build in the usual make; make check;
    # make install order.
    - ./recipe/test-{{ flavour }}.sh
    - cd src/libexactreal && make install

requirements:
  build:
    - libtool
    - automake
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - e-antic 1.*
    - arb
    - gmp
    # requirement of make check which also runs benchmarks
    - gtest
    - benchmark
  run_exports:
    - libexactreal {{ version }}

outputs:
  - name: libexactreal
  - name: pyexactreal
    build:
      skip: True  # [win]
      skip: True  # [osx]
    script: install-python.sh
    requirements:
      build:
        - libtool
        - automake
        - {{ compiler('cxx') }}
      host:
        - boost-cpp
        - e-antic 1.*
        - arb
        - gmp
      run:
        - libexactreal =={{ version }}
        # cppyy, not packaged in conda-forge yet
        - pyeantic
    # We cannot test that that the import works since cppyy is not on conda-forge yet
    #test:
    #  imports:
    #    - pyexactreal

about:
  home: https://github.com/flatsurf/exact-real
  license: GPL2
  license_file: COPYING
  summary: Finite Real Submodules powered by E-ANTIC

extra:
  recipe-maintainers:
    - saraedum
    - videlec
