# See https://github.com/conda/conda-build/issues/2666 for the missing tag
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
# conda-smithy assumes that the build number is >= 1000 when building with the new anaconda compilers,
# this probably is not important but make_build_number otherwise complains during the build
{% set build_number = (environ.get('GIT_DESCRIBE_NUMBER')|int + 1000)|string %}
{% set build_string = "master_" + ((build_flavour + "_") if build_flavour != "release" else "") + build_number %}

package:
  name: exact-real
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

_build: &build

build:
  number: {{ build_number }}
  string: {{ build_string }}
  # e-antic is not available on Windows yet
  skip: True  # [win]
  # e-antic is not available on macOS yet
  skip: True  # [osx]

# Since we run all our CI (static checks, benchmarks, coverage, …) through our
# main build.sh script, it needs to have all the requirements to build & run
# all parts of this repository.
# Packagers might prefer to build the subdirectories completely separately and
# have them depend on each other.
requirements:
  build:
    - libtool
    - automake
    - {{ compiler('cxx') }}
    # requirements for ASV benchmarks
    - git
    # requirements for clang-format
    - clangdev ==8.0.0
  host:
    # compile-time dependencies of libexactreal
    - boost-cpp
    - e-antic 1.*
    - arb
    - gmp
    # We pin to an explicit version of Python here; since the Python part is
    # noarch:python, the version does not matter. However, we need the same
    # version when doing "make install" so that files go into the site-packages
    # directory that was determined by ./configure.
    - python 3.7.*
    # enable test/pyexactreal tests in ./configure
    - pytest
    - cppyy
    - pyeantic
    # enable test/libexactreal tests in ./configure
    - gtest
    - benchmark
    # enable check-valgrind in ./configure
    - valgrind >=3.15.0
    # requirements for ASV benchmarks
    - asv
    # to run optional SageMath tests
    - sagelib
    - pip
    # to enable serialization in Python/SageMath tests
    - cereal

outputs:
  - name: libexactreal
    script: install-libexactreal.sh
    build:
      number: {{ build_number }}
      string: {{ build_string }}
{%- if build_flavour and build_flavour != 'release' %}
      features:
        - {{ build_flavour }}
{% endif %}
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - boost-cpp
        - e-antic 1.*
        - arb
        - gmp
    run_exports:
      # We pin the version of libexactreal exactly since we do not want to
      # bother with incompatibilities in our nightly builds.
      - {{ pin_subpackage('libexactreal', exact=True) }}
  - name: pyexactreal
    build:
      number: {{ build_number }}
      string: {{ build_string }}
{%- if build_flavour and build_flavour != 'release' %}
      features:
        - {{ build_flavour }}
{% endif %}
      noarch: python
    script: install-pyexactreal.sh
    requirements:
      host:
        - python 3.7.*
        - setuptools
      run:
        # We pin the version of libexactreal exactly since we do not want to
        # bother with incompatibilities in our nightly builds.
        - {{ pin_subpackage('libexactreal', exact=True) }}
        - cppyy
        - pyeantic
        - python
        - boost-cpp
        - cereal
{%- if build_flavour == 'release' %}
    test:
      imports:
        - pyexactreal
{% endif %}

about:
  home: https://github.com/flatsurf/exact-real
  license: GPL2
  license_file: COPYING
  summary: Finite Real Submodules powered by E-ANTIC

extra:
  recipe-maintainers:
    - saraedum
    - videlec
