{% set version = '0.0.0' %}
{% set build_number = '0' %}

package:
  name: libarbxx
  version: {{ version }}

source:
  path: ../../

build:
  number: {{ build_number }}
  # e-antic is not available on Windows yet
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage("libarbxx", max_pin="x") }}

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
  host:
    - arb {{ arb }}
    - boost-cpp {{ boost_cpp }}
    - gmp {{ gmp }}

test:
  commands:
    - test -f ${PREFIX}/lib/libarbxx.so

about:
  home: https://github.com/flatsurf/arbxx
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: C++ Wrappers for Arb
