# This file lists the dependencies needed to build and test all of libarbxx.
# # Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: libarbxx-build
channels:
  - conda-forge
  - defaults
dependencies:
  - arb>=2.21,<2.22
  - automake
  - benchmark
  - boost-cpp==1.74.0
  # see https://github.com/byexamples/byexample/issues/220
  - byexample==10.4.0
  - coreutils
  # see https://github.com/wlav/cppyy/issues/32, with newer versions we cannot test operators that throw.
  - cppyy==1.9.5
  - cxx-compiler
  - gmp>6,<7
  - libtool
  - make
  - parallel
  # valgrind is only needed for make check-valgrind
  # - valgrind
