{% set version = '0.0.0' %}
{% set build_number = '0' %}

package:
  name: pyarbxx
  version: {{ version }}

source:
  path: ../../

build:
  number: {{ build_number }}

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - libarbxx
  run:
    - python
    - boost-cpp
    - cppyy
    - cppyythonizations >=1.1.3,<2

test:
  imports:
    - pyarbxx

about:
  home: https://github.com/flatsurf/arbxx
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: C++ Wrappers for Arb
