name: Code Coverage
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

jobs:
  codecov:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "flatsurf,conda-forge", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba install --yes --quiet python=${{ matrix.python }}
          mamba env update --quiet -n test -f libexactreal/environment.yml
          mamba env update --quiet -n test -f pyexactreal/environment.yml
          conda list
      - name: build & test
        shell: bash -l {0}
        run: |
          ./bootstrap
          ./configure --prefix="$PREFIX" CXXFLAGS="$CXXFLAGS --coverage -O0 -UNDEBUG" --without-benchmark
          make check
      - name: create & post coverage report
        shell: bash -l {0}
        run: |
          pushd libexactreal/test
          find -type f -name '*.gcda' -exec gcov -pbs ../../../exact-real '{}' ';'
          popd
          pushd libexactreal/src
          find -type f -name '*.gcda' -exec gcov -pbs ../../../exact-real '{}' ';'
          popd
          curl -s https://codecov.io/bash | bash -s - -X gcov -R `pwd` .

env:
  MAKEFLAGS: -j2
