name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

jobs:
  test-libexactreal:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - target: check
          - target: check
            environment: binder
          - target: check-valgrind
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - name: install valgrind and libc debug symbols
        run: |
          sudo apt update
          sudo apt install libc6-dbg valgrind
        if: ${{ matrix.target == 'check-valgrind' }}
      - name: build flags
        id: flags
        run: |
          echo "::set-output name=configure::"`[[ ${{ runner.os }} == "Linux" ]] && echo "--with-version-script"`
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "flatsurf,conda-forge", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f libexactreal/environment.yml
          conda list
        if: ${{ matrix.environment != 'binder' }}
      - name: Create binder environment
        shell: bash -l {0}
        run: |
          wget -O repo2docker.yml https://github.com/jupyterhub/repo2docker/raw/main/repo2docker/buildpacks/conda/environment.yml
          mamba install -n test --quiet -y pytest pytest-xdist byexample
          mamba env update -n test --quiet -f repo2docker.yml
          mamba env update -n test --quiet -f binder/environment.yml
          conda list
        if: ${{ matrix.environment == 'binder' }}
      - name: make ${{ matrix.target }}
        shell: bash -l {0}
        run: |
          echo "::group::bootstrap"
          cd libexactreal
          ./bootstrap

          echo "::group::configure"
          export CXXFLAGS="$CXXFLAGS -UNDEBUG -g3"
          ./configure --prefix="$PREFIX" --without-benchmark ${{ steps.flags.outputs.configure }}

          echo "::group::make"
          make V=1

          echo "::group::make ${{ matrix.target }}"
          make V=1 ${{ matrix.target }} VALGRIND_SUPPRESSIONS_FILES=`pwd`/../tools/valgrind/conda.supp
      - uses: flatsurf/actions/show-logs@main
        if: ${{ always() }}
  test-pyexactreal:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - target: check
            python: "3.6"
          - target: check
            python: "3.7"
          - target: check
            python: "3.8"
          - target: check
            python: "3.9"
          - target: check-valgrind
            python: "3.9"
          - target: check
            environment: binder
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - name: install valgrind and libc debug symbols
        run: |
          sudo apt update
          sudo apt install libc6-dbg valgrind
        if: ${{ matrix.target == 'check-valgrind' }}
      - name: build flags
        id: flags
        run: |
          echo "::set-output name=configure::"`[[ ${{ runner.os }} == "Linux" ]] && echo "--with-version-script"``[[ '${{ matrix.environment }}' == "binder" ]] && echo "--without-sage"`
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "flatsurf,conda-forge", python-version: "${{ matrix.python }}", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f libexactreal/environment.yml
          mamba env update --quiet -n test -f pyexactreal/environment.yml
          conda list
        if: ${{ matrix.environment != 'binder' }}
      - name: Create binder environment
        shell: bash -l {0}
        run: |
          wget -O repo2docker.yml https://github.com/jupyterhub/repo2docker/raw/main/repo2docker/buildpacks/conda/environment.yml
          mamba install -n test --quiet -y pytest pytest-xdist byexample
          mamba env update -n test --quiet -f repo2docker.yml
          mamba env update -n test --quiet -f binder/environment.yml
          conda list
        if: ${{ matrix.environment == 'binder' }}
      - name: make ${{ matrix.target }}
        shell: bash -l {0}
        run: |
          echo "::group::bootstrap"
          ./bootstrap

          echo "::group::configure"
          export CXXFLAGS="$CXXFLAGS -UNDEBUG -g3"
          ./configure --prefix="$PREFIX" --without-benchmark ${{ steps.flags.outputs.configure }}

          echo "::group::make"
          make V=1

          echo "::group::make ${{ matrix.target }}"
          cd pyexactreal
          make V=1 ${{ matrix.target }} VALGRIND_SUPPRESSIONS_FILES=`pwd`/../tools/valgrind/conda.supp
      - uses: flatsurf/actions/show-logs@main
        if: ${{ always() }}
  distcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "flatsurf,conda-forge", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f libexactreal/environment.yml
          mamba env update --quiet -n test -f pyexactreal/environment.yml
          conda list
      - name: make distcheck
        shell: bash -l {0}
        run: |
          ./bootstrap
          ./configure --prefix="$PREFIX"
          make distcheck
      - uses: flatsurf/actions/show-logs@main
        if: ${{ always() }}

env:
  MAKEFLAGS: -j2
